version: '2.1'
services:
    redis:
        image: redis:4.0.11
        restart: always
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - /srv/dockerData/airflow/pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: test/ariflow
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:
            - /srv/dockerData/airflow/dags:/usr/local/airflow/dags
            - /srv/dockerData/airflow/sql:/usr/local/airflow/sql
            - /srv/dockerData/airflow/plugins:/usr/local/airflow/plugins
            - /srv/dockerData/airflow/logs/webserver:/usr/local/airflow/logs
        ports:
            - "20080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: test/ariflow
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: test/ariflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - /srv/dockerData/airflow/dags:/usr/local/airflow/dags
            - /srv/dockerData/airflow/sql:/usr/local/airflow/sql
            - /srv/dockerData/airflow/plugins:/usr/local/airflow/plugins
            - /srv/dockerData/airflow/logs/scheduler:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: test/ariflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /srv/dockerData/airflow/dags:/usr/local/airflow/dags
            - /srv/dockerData/airflow/sql:/usr/local/airflow/sql
            - /srv/dockerData/airflow/plugins:/usr/local/airflow/plugins
            - /srv/dockerData/airflow/logs/worker:/usr/local/airflow/logs
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        command: worker
